Added login form to header
erikpersson0884/DAT257-Agile-software-project-management pull request #41
Opened 2024-04-16 08:52 UTC by IsacSnecker

2024-04-16 13:50 UTC, Pontus-Wikstrom requested changes
Check the comments provided, overall it looks good but there's need of changes. Change pixel values, check the margins and formatting

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/Header.css
> +    margin-left:32vw;
Change margin to auto, seems to work better with different screensizes

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/Header.css
> +    width: 60px;
Use rem as value, don't use pixels as they are fixated

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/Header.css
> +.reactedForm {
Should be able to remove this

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/Header.css
> +    right: 10px;
use rem as values

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/Header.tsx
There's 2 Home-links right now, check if you can remove one of them or write a statement that makes the instance of the home in the mapping to default to /

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/UserLogo.css
> +    width: 60px;
Use rem

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/UserLogo.css
> +    margin-left:65vw;
Not really sure why userLogo has 2 different css instances, one here and one in Header.css, maybe remove one of them? Also, what's the difference between this margin-left and the margin-left in Header.css?

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/UserLogo.css
> +    top: calc(100% + 5px); /* Position it just below the user logo */
Use rem

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/UserLogo.tsx
> +
remove newline

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/Header/UserLogo.tsx
> +
remove newline

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/InformationPage/InformationPage.tsx
> +
remove newline

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/InformationPage/InformationPage.tsx
> +import LoginForm from "../LoginForm/LoginForm";
is it neccessary that we import LoginForm in different pages?

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/LoginForm/LoginForm.css
Overall looks good, change the pixel values to rem values instead, the input boxes seems to be a little bit off-centered for me

2024-04-16 13:50 UTC, Pontus-Wikstrom commented on Frontend/DAT257_Website/src/Components/LoginForm/LoginForm.tsx
Looks good, check formatting

2024-04-17 11:34 UTC, erikpersson0884 commented on Frontend/DAT257_Website/src/Components/Header/Header.tsx
Should be resolved by removing "home" from navList list since the home navigation have special code that will not work with the for loop

2024-04-17 20:59 UTC, Pontus-Wikstrom approved these changes
Let someone else also look through the code now as I've worked with the branch

2024-04-18 13:01 UTC, erikpersson0884 approved these changes

2024-04-18 13:01 UTC, merged